[tool.poetry]
name = "stupidb"
version = "0.1.0"
packages = [{ include = "stupidb" }]
# don't ship tests with the install
exclude = ["stupidb/tests"]
homepage = "https://github.com/cpcloud/stupidb"
repository = "https://github.com/cpcloud/stupidb"
documentation = "https://stupidb.readthedocs.io"
description = "The stupidest of all the databases."
authors = ["Phillip Cloud <cpcloud@gmail.com>"]
maintainers = ["Phillip Cloud <cpcloud@gmail.com>"]
license = "Apache-2.0"
readme = "README.rst"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.7",
]

[tool.poetry.dependencies]
python = "^3.8"
cytoolz = "0.11.0"
imageio = { version = "2.9.0", optional = true }
networkx = { version = "2.5.1", optional = true }
pydot = { version = "1.4.2", optional = true }

[tool.poetry.extras]
animation = ["networkx", "pydot", "imageio"]

[tool.poetry.dev-dependencies]
black = "20.8b1"
bump2version = "1.0.1"
conda-lock = "0.11.0"
coverage = "5.5"
flake8 = "3.9.2"
ipython = "7.25.0"
isort = "5.7.0"
mypy = "0.812"
mypy_extensions = "0.4.3"
pydocstyle = "6.1.1"
pytest = "6.2.2"
sphinx = "4.1.1"
sphinx-autodoc-typehints = "1.12.0"
python-semantic-release = "7.16.2"

[tool.semantic_release]
version_toml = "pyproject.toml:tool.poetry.version"
branch = "nix-env"
upload_to_pypi = false
build_command = "nix-shell --pure -p poetry --run 'poetry build'"

[tool.conda-lock]
channels = ["conda-forge", "defaults"]

[tool.pytest]
xfail_strict = true
addopts = [
    "--ignore=site-packages",
    "--ignore=dist-packages",
    "--strict-markers"
]
norecursedirs = ["site-packages", "dist-packages"]

[tool.black]
line_length = 88

[tool.isort]
line_length = 88
profile = "black"

[tool.pydocstyle]
convention = "numpy"
add_ignore = ["D105", "D213", "D203"]

[tool.mypy]
ignore_missing_imports = true
# untyped things
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
# Any handling
disallow_any_unimported = false
disallow_any_expr = false
disallow_any_decorated = false
disallow_any_explicit = false
disallow_any_generics = false
disallow_subclassing_any = false
# None/Optional handling
no_implicit_optional = true
# show more context on failure
show_error_context = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
