[tool.poetry]
name = "stupidb"
version = "4.4.0"
packages = [{ include = "stupidb" }]
# don't ship tests with the install
exclude = ["stupidb/tests"]
homepage = "https://github.com/cpcloud/stupidb"
repository = "https://github.com/cpcloud/stupidb"
documentation = "https://stupidb.readthedocs.io"
description = "The stupidest of all the databases."
authors = ["Phillip Cloud <cpcloud@gmail.com>"]
maintainers = ["Phillip Cloud <cpcloud@gmail.com>"]
license = "Apache-2.0"
readme = "README.rst"
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Natural Language :: English",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
]

[tool.poetry.dependencies]
python = "^3.7"
cytoolz = "^0.11.0"
importlib-metadata = { version = "^4.6.1", python = "<3.8" }
pydot = { version = "^1.4.2", optional = true }

[tool.poetry.dev-dependencies]
black = "^20.8b1"
coverage = "^5.5"
flake8 = "^3.9.2"
isort = "^5.9.3"
mypy = "^0.812"
mypy_extensions = "^0.4.3"
pydocstyle = "^6.1.1"
pytest = "^6.2.2"
sphinx = "^4.1.2"
sphinx-autodoc-typehints = "^1.12.0"

[tool.poetry.extras]
animation = ["pydot"]

[tool.semantic_release]
version_toml = "pyproject.toml:tool.poetry.version"
version_variable = ["docs/conf.py:version", "docs/conf.py:release"]
branch = "master"
upload_to_pypi = true
build_command = "pip install poetry && poetry build"

[tool.pytest.ini_options]
xfail_strict = true
addopts = [
  "--ignore=site-packages",
  "--ignore=dist-packages",
  "--strict-markers"
]
markers = ["animate"]
norecursedirs = ["site-packages", "dist-packages"]

[tool.black]
line_length = 88

[tool.isort]
line_length = 88
profile = "black"

[tool.pydocstyle]
convention = "numpy"
add_ignore = ["D105", "D213", "D203"]
match-dir = "stupidb"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
